name: flutter_arbiter
description: Website for Flutter Arbiter
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  static_shock: 0.0.2

dependency_overrides:
  static_shock:
    git:
      url: git@github.com:Flutter-Bounty-Hunters/static_shock.git
      path: packages/static_shock
      ref: 71_draft-mode

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
